volumes:
  kittygram_pg_data:
  static:
  media:

services:
  kittygram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data
    restart: unless-stopped  
  backend:
    build: ./backend/
    depends_on:
      - kittygram_db
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    restart: unless-stopped  
  frontend:
    env_file: .env
    build: ./frontend/
    command: sh -c "cp -r /app/build/. /static/ && tail -f /dev/null"
    volumes:
     - static:/static
  gateway:
    build: ./nginx/
    depends_on:
      - backend
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media
    restart: unless-stopped
