# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  kittygram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alinagay/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: alinagay/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: alinagay/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/app/media
    ports:
      - 9000:80